### ISSUE TITLE
Error when using UCSC Repeats

### ISSUE THREAD

**Issue by SJRussell** [mlbendall/telescope_annotation_db#2]
Hello! Thank you for creating this much needed tool, I look forward to analyzing my data.

I have paired end illumina sequencing data that I'm trying to run through Telescope v 1.0.3. The test worked fine after installation, and then my data appeared to map properly when using "transcripts.gtf" from your Hg38 build. I did get this error:
`[E::idx_find_and_load] Could not retrieve index file for '../star_mapped_ERCC/B5_S8_L001Aligned.sortedByCoord.out.bam'`
But the command still completed and from what I could tell this didn't effect the output:
`## RunInfo      version:1.0.3   annotated_features:28513        total_fragments:177317  pair_mapped:164421      pair_mixed:12896        single_mapped:0 unmapped:0      unique:170428   ambig:6889      overlap_unique:5099     overlap_ambig:292`
Does this look like typical mapping output?

I didn't see some of the common TEs in your gtf file (such as Alu) so I opted to try a complete repeat database from UCSC. I used table browser to output a gtf, which starts like this:
```
chr1    hg38_rmsk       exon    67108754        67109046        1892.000000     +       .       gene_id "L1P5"; transcript_id "L1P5";
chr1    hg38_rmsk       exon    8388316 8388618 2582.000000     -       .       gene_id "AluY"; transcript_id "AluY";
chr1    hg38_rmsk       exon    25165804        25166380        4085.000000     +       .       gene_id "L1MB5"; transcript_id "L1MB5";
chr1    hg38_rmsk       exon    33554186        33554483        2285.000000     -       .       gene_id "AluSc"; transcript_id "AluSc";
chr1    hg38_rmsk       exon    41942895        41943205        2451.000000     -       .       gene_id "AluY"; transcript_id "AluY_dup1";
chr1    hg38_rmsk       exon    50331337        50332274        1587.000000     +       .       gene_id "HAL1"; transcript_id "HAL1";
chr1    hg38_rmsk       exon    58719765        58720546        1393.000000     +       .       gene_id "L2a"; transcript_id "L2a";
chr1    hg38_rmsk       exon    75496058        75497775        5372.000000     +       .       gene_id "L1MA9"; transcript_id "L1MA9";
...
```
However, I'm getting an error. Here is the command and the output:
```
user@System:/data/project/telescope$ telescope assign --attribute gene_id ../star_mapped_ERCC/B5_S8_L001Aligned.sortedByCoord.out.bam ../UCSC_Repeats.gtf
2021-07-19 14:34:51 INFO
Version:                          1.0.3
Input Options
    samfile:                      ../star_mapped_ERCC/B5_S8_L001Aligned.sortedByCoord.out.bam
    gtffile:                      ../UCSC_Repeats.gtf
    attribute:                    gene_id
    no_feature_key:               __no_feature
    ncpu:                         1
    tempdir:                      None
Reporting Options
    quiet:                        False
    debug:                        False
    logfile:                      <stderr>
    outdir:                       .
    exp_tag:                      telescope
    updated_sam:                  False
Run Modes
    reassign_mode:                exclude
    conf_prob:                    0.9
    overlap_mode:                 threshold
    overlap_threshold:            0.2
    annotation_class:             intervaltree
Model Parameters
    pi_prior:                     0
    theta_prior:                  200000
    em_epsilon:                   1e-07
    max_iter:                     100
    use_likelihood:               False
    skip_em:                      False
 (from run in telescope_assign.py:197)
[E::idx_find_and_load] Could not retrieve index file for '../star_mapped_ERCC/B5_S8_L001Aligned.sortedByCoord.out.bam'
2021-07-19 14:34:51 INFO     Loading annotation...                                        (from run in telescope_assign.py:205)
Traceback (most recent call last):
  File "/home/stewart/miniconda3/bin/telescope", line 10, in <module>
    sys.exit(main())
  File "/home/stewart/miniconda3/lib/python3.8/site-packages/telescope/__main__.py", line 95, in main
    args.func(args)
  File "/home/stewart/miniconda3/lib/python3.8/site-packages/telescope/telescope_assign.py", line 207, in run
    annot = Annotation(opts.gtffile, opts.attribute)
  File "/home/stewart/miniconda3/lib/python3.8/site-packages/telescope/utils/_annotation_intervaltree.py", line 52, in __init__
    assert len(mergeable) == 1, "Error"
AssertionError: Error
```
And suggestions? Thanks in advance!

**Comment by SJRussell** [comment]
In case you were wondering the source of the gtf:
![image](https://user-images.githubusercontent.com/16674389/126216833-b6511ad3-c4f2-408f-bf50-24a0c4f70e5a.png)

**Comment by JianGuoZhou3** [comment]
Hi @SJRussell  did you solve this error?
